<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fresh.xy</groupId>
        <artifactId>xy-common-parent</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.fresh.xy</groupId>
    <artifactId>xy-rmq-starter</artifactId>
    <version>${xy-rmq.version}</version>
    <packaging>jar</packaging>
    <name>xy-rmq-starter</name>
    <description>xy-rmq-starter</description>

    <properties>
        <skipTests>true</skipTests>
    </properties>

    <dependencies>
        <!-- xy-common -->
        <dependency>
            <groupId>com.fresh.xy</groupId>
            <artifactId>xy-common</artifactId>
        </dependency>
        <!-- rocketmq -->
        <dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-client</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
        <!-- rocketmq-spring-boot-starter -->
        <!--<dependency>
            <groupId>org.apache.rocketmq</groupId>
            <artifactId>rocketmq-spring-boot-starter</artifactId>
        </dependency>-->
    </dependencies>


</project>
