<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.fresh.xy</groupId>
        <artifactId>xy-common-parent</artifactId>
        <version>1.0.0</version>
    </parent>
    <groupId>com.fresh.xy</groupId>
    <artifactId>xy-common</artifactId>
    <version>${xy-common.version}</version>
    <packaging>jar</packaging>
    <name>xy-common</name>
    <description>xy-common</description>

    <properties>
        <skipTests>true</skipTests>
    </properties>

    <dependencies>
        <!-- fresh-core -->
        <dependency>
            <groupId>com.fresh</groupId>
            <artifactId>fresh-core</artifactId>
        </dependency>

        <!-- 依赖 mybaits-plus 的枚举注解，entity 注解 -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-core</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-extension</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.datatype</groupId>
            <artifactId>jackson-datatype-jsr310</artifactId>
        </dependency>
        <dependency>
            <groupId>javax.validation</groupId>
            <artifactId>validation-api</artifactId>
        </dependency>
    </dependencies>

</project>
